/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MapRouteImport } from './routes/map'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as CreateRequestRouteImport } from './routes/create-request'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as PropertyIdRouteImport } from './routes/property.$id'
import { Route as ChatIdRouteImport } from './routes/chat.$id'

const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRequestRoute = CreateRequestRouteImport.update({
  id: '/create-request',
  path: '/create-request',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/create-request': typeof CreateRequestRoute
  '/favorites': typeof FavoritesRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/requests': typeof RequestsRoute
  '/chat/$id': typeof ChatIdRoute
  '/property/$id': typeof PropertyIdRoute
  '/chat/': typeof ChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/create-request': typeof CreateRequestRoute
  '/favorites': typeof FavoritesRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/requests': typeof RequestsRoute
  '/chat/$id': typeof ChatIdRoute
  '/property/$id': typeof PropertyIdRoute
  '/chat': typeof ChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/create-request': typeof CreateRequestRoute
  '/favorites': typeof FavoritesRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/requests': typeof RequestsRoute
  '/chat/$id': typeof ChatIdRoute
  '/property/$id': typeof PropertyIdRoute
  '/chat/': typeof ChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/create-request'
    | '/favorites'
    | '/map'
    | '/profile'
    | '/requests'
    | '/chat/$id'
    | '/property/$id'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/create-request'
    | '/favorites'
    | '/map'
    | '/profile'
    | '/requests'
    | '/chat/$id'
    | '/property/$id'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/create-request'
    | '/favorites'
    | '/map'
    | '/profile'
    | '/requests'
    | '/chat/$id'
    | '/property/$id'
    | '/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRoute
  CreateRequestRoute: typeof CreateRequestRoute
  FavoritesRoute: typeof FavoritesRoute
  MapRoute: typeof MapRoute
  ProfileRoute: typeof ProfileRoute
  RequestsRoute: typeof RequestsRoute
  ChatIdRoute: typeof ChatIdRoute
  PropertyIdRoute: typeof PropertyIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-request': {
      id: '/create-request'
      path: '/create-request'
      fullPath: '/create-request'
      preLoaderRoute: typeof CreateRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRoute,
  CreateRequestRoute: CreateRequestRoute,
  FavoritesRoute: FavoritesRoute,
  MapRoute: MapRoute,
  ProfileRoute: ProfileRoute,
  RequestsRoute: RequestsRoute,
  ChatIdRoute: ChatIdRoute,
  PropertyIdRoute: PropertyIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
